
export const MEMBERS: string[] = [
  "abhishek_yadav_m",
  "abi_lasha-2006",
  "ABISHEK_K_M",
  "ABSrinitha",
  "Aishu_0711",
  "Ajay_Kumar-011",
  "Akshaya_1020",
  "Akshaya_devakumar14",
  "akshcs013",
  "Andhena_Nireesha",
  "andrea_mercy06",
  "ANJALI_E_S",
  "AnuR_016",
  "Anusuya_6077",
  "mokshavardhansai",
  "Arthy_I",
  "Aswinkumar_20",
  "ATMAKURIRAVITEJA",
  "tullip",
  "cr6SUzbgKV",
  "Srayan_brahma_006",
  "bhavana126",
  "BHAVISH_10",
  "BiradavoluNoshitha18",
  "8yhIv7XaJh",
  "dhushyanth_______reddy",
  "Chandra033",
  "chandru00",
  "kchethan_24",
  "zQMniHKEPh",
  "AnusriChirukurapati",
  "tejeshvarma2006",
  "deepak_m_",
  "Deepika_S29",
  "Dhanush_Rm",
  "dharmesh_1308",
  "dhashu",
  "dineshkumaar9025067808",
  "_Divya_02",
  "00Ej9LcSIS",
  "Abitha08",
  "GADDAMKOUSHIK",
  "gajulavishnu_15",
  "thanvi_chinni",
  "gandikotaravi",
  "Ganesh0902",
  "giritv",
  "HarshiniNew",
  "sai_rohith2303",
  "gowtham_21_05",
  "Gunashree_29",
  "Balaji056",
  "officialharikrishnans",
  "Kamali_665",
  "harish__46__",
  "SwtwHjA0s8",
  "infantebsin",
  "Janani_Sureshkumar",
  "__Jeevitha__M",
  "8nk3MxYq2i",
  "jyotheesh_81",
  "kamaleshag96",
  "PoojaReddy084",
  "kani1910",
  "bhanusruthi",
  "kaushik0325kumar",
  "Kavithalakshmi4",
  "KaviyaKumar_V",
  "keerthivasan_01",
  "keshh_ika06",
  "Kiranmaya-official",
  "Kiruthika_Sankar",
  "Kishoore_29",
  "SaiReddy_23",
  "dhanya_sree102005",
  "Jeswitha28",
  "gitkoti200",
  "sricharitha28",
  "kowsalya_2005",
  "VEbxmKj5a0",
  "LAHARI-_2006",
  "laksh212",
  "Lithika_D",
  "THfpmrsVNS",
  "Xnj7rVqDN2",
  "6j8z1EdauU",
  "jittu1110",
  "saijyoshna12",
  "MANIBARATHI1718",
  "111623102115",
  "mathika04",
  "Mathumitha_27",
  "midhu_0309",
  "5c5v5NVXXQ",
  "moha_106",
  "monika2027",
  "monish_25",
  "mridu_2810",
  "Murali_2701",
  "MunagapatiRishitha005",
  "Nancy_19_",
  "Nanda_55",
  "eNSHStfmYF",
  "OvZRk5AH75",
  "Nethra_Balan_G",
  "niki_676",
  "dir__7878",
  "ravillanishanth2005",
  "nithinsage",
  "MR_NITHISH_26",
  "nithishm_2005",
  "Nithya0221",
  "NItishrameshpp",
  "parnashanmukasaisandeep",
  "Pavithra_Manivannan",
  "penjcs_var",
  "ranjitha2809",
  "pragadeesh_3008",
  "pramodram",
  "pras_07",
  "_riya_harshini_",
  "PRIYA_-23",
  "pavan__05",
  "Rackshita",
  "Raghavi_081204",
  "raja_28",
  "rajasakthieswaran",
  "Rakshitha_1304",
  "S-Ramitha_7",
  "Rangineni_SaiNithish",
  "K9xId0RviY",
  "IB35hgMtwf",
  "Sachin_Kumar07",
  "sahaana__je",
  "Sahana_Krishnan29",
  "SAIDHANUSH_2909",
  "Sai_krishna141",
  "T7RixMPjnx",
  "Samhita19",
  "sanjanashreedd",
  "saranya181",
  "FyYp7p7lVn",
  "Sarimitha",
  "SATHYA__C",
  "savitha2226",
  "WzKhcOdAsT",
  "Shalini_188",
  "Shanmathi-C",
  "Sharmi24",
  "Shammujeenu_7483",
  "7TvIJb5ndZ",
  "Shree_harine",
  "shyam545",
  "smirti",
  "Sneha9732",
  "PravalikaSomisetty",
  "sreeharshini2005",
  "srinivasangv1608",
  "sriranjaniS",
  "vishwaa55",
  "sunil-108",
  "SUYAMBULINGAMM",
  "decimusmaximusmeridius",
  "Chayank__T",
  "Manu_207",
  "tharun_raj_28",
  "mani00299",
  "lalith_manjunath_reddy",
  "yashwanth_2912",
  "9014767760",
  "N-Varnika",
  "varsha_shree1604",
  "vasanth_6299",
  "Vasuntra",
  "vigneshpraveen-official",
  "vijay07-vj",
  "vikramkumarofficial",
  "VontimittaJaswanth",
  "Xavier_04",
  "Yaminii02",
  "yaswanth1801",
  "yeswanth_2005",
  "yogalakshmissankarm",
  "21092004",
  "zakiya_0212",
  "RazzorPets",
  "Abinash_55",
  "X6g2NMWDMx",
  "Lavanya__2005",
  "darwingowtham",
  "RUPAKRITVIK",
  "avanthikaaa",
  "lxGppUCCOw",
  "UJCyYkb26w",
  "samadarmi",
  "vLMN2LmOqe",
  "uC13BEcWC9",
  "Kalai0605",
  "tgCYp40LtP",
];

export const MEMBER_DISPLAY: Record<string, string> = {
  "abhishek_yadav_m" : "ABHISHEK YADAV M",
"abi_lasha-2006" : "ABILASHA V",
"ABISHEK_K_M" : "ABISHEK K M",
"ABSrinitha" : "ADAKUPPAM BALACHANDRA SRINITHA",
"Aishu_0711" : "AISHWARYA S",
"Ajay_Kumar-011" : "AJAY KUMAR CHANDRAKUMAR",
"Akshaya_1020" : "AKSHAYA B",
"Akshaya_devakumar14" : "AKSHAYA D",
"akshcs013" : "AKSHAYA N",
"Andhena_Nireesha" : "ANDHENA NIREESHA",
"andrea_mercy06" : "ANDREA MERCY S",
"ANJALI_E_S" : "ANJALI E S",
"AnuR_016" : "ANU R",
"Anusuya_6077" : "ANUSUYA S",
"mokshavardhansai" : "ARIGA MOKSHA VARDHAN SAI",
"Arthy_I" : "ARTHY I",
"Aswinkumar_20" : "ASWIN KUMAR U",
"ATMAKURIRAVITEJA" : "ATMAKURI RAVI TEJA",
"tullip":"BAARGAVI",
"cr6SUzbgKV" : "BARATH A S",
"Srayan_brahma_006" : "BATTU SRAYAN BRAHMA",
"bhavana126" : "BHAVANA R L",
"BHAVISH_10" : "BHAVISH B",
"BiradavoluNoshitha18" : "BIRADAVOLU NOSHITHA",
"8yhIv7XaJh" : "BOJJA MAHESH",
"dhushyanth_______reddy" : "CHALLA DHUSHYANTH",
"Chandra033" : "CHANDRALEKHA A",
"chandru00" : "CHANDRU K R",
"kchethan_24" : "CHETHAN CHAKRAVARTHI K",
"zQMniHKEPh" : "CHETHAN REDDY N",
"AnusriChirukurapati" : "CHIRUKURAPATI VENKATA ANUSRI",
"tejeshvarma2006" : "DASARAJU TEJESH VARMA",
"deepak_m_" : "DEEPAK M",
"Deepika_S29" : "DEEPIKA S",
"Dhanush_Rm" : "DHANUSH R M",
"dharmesh_1308" : "DHARMESH M",
"dhashu" : "DHASHUBHAN KUMAR S",
"dineshkumaar9025067808" : "DINESH KUMAAR K",
"_Divya_02" : "DHIVYA D",
"00Ej9LcSIS" : "ELAKKIYA R",
"Abitha08" : "GADAMSETTI ABITHA",
"GADDAMKOUSHIK" : "GADDAM KOUSHIK",
"gajulavishnu_15" : "GAJULA VISHNU SAI",
"thanvi_chinni" : "GALI THANVIKA",
"gandikotaravi" : "GANDIKOTA RAVI CHANDRA",
"Ganesh0902" : "GANESH U",
"giritv" : "GIRI T V",
"HarshiniNew" : "GOGA HARSHINI",
"sai_rohith2303" : "GOTTI SAI ROHITH",
"gowtham_21_05" : "GOWTHAM S",
"Gunashree_29" : "GUNASHREE V",
"Balaji056" : "GUNDLURU BALAJI",
"officialharikrishnans" : "HARIKRISHNAN S",
"Kamali_665" : "HARINI KAMALI R",
"harish__46__" : "HARISH V",
"SwtwHjA0s8" : "HEMAPRIYA J",
"infantebsin" : "INFANT MARIA EBSIN A",
"Janani_Sureshkumar" : "JANANI S",
"__Jeevitha__M" : "JEEVITHA M",
"8nk3MxYq2i" : "JEEVITHA V S",
"jyotheesh_81" : "JYOTHEESH K",
"kamaleshag96" : "KAMALESH A G",
"PoojaReddy084" : "KANASANI POOJA REDDY",
"kani1910" : "KANIMOZHI K",
"bhanusruthi" : "KARADI BHANU SRUTHI",
"kaushik0325kumar" : "KAUSHIK KUMAR R M",
"Kavithalakshmi4" : "KAVITHA LAKSHMI A",
"KaviyaKumar_V" : "KAVIYA V",
"keerthivasan_01" : "KEERTHIVASAN V",
"keshh_ika06" : "KESHIKA A C",
"Kiranmaya-official" : "KIRANMAYA L",
"Kiruthika_Sankar" : "KIRUTHIKA P S",
"Kishoore_29" : "KISHOORE R",
"SaiReddy_23" : "KOLAGATLA MANIKANTA SAI REDDY",
"dhanya_sree102005" : "KONDURU DHANYA SREE",
"Jeswitha28" : "KOTA REDDY JESWITHA",
"gitkoti200" : "KOTEESWARAN A",
"sricharitha28" : "KOTHA MUNI SRI CHARITHA",
"kowsalya_2005" : "KOWSALYA M",
"VEbxmKj5a0" : "LAKSHITHA D S",
"LAHARI-_2006" : "LAHARI D",
"laksh212" : "LAKSHMANAN VEMULA",
"Lithika_D" : "LITHIKA D",
"THfpmrsVNS" : "MADHUMITHA D",
"Xnj7rVqDN2" : "MADHUMITHA R",
"6j8z1EdauU" : "MADHUMITHA S",
"jittu1110" : "MAJETI NVSS JITHENDRA",
"saijyoshna12" : "MALLENI SAI JYOSHNA",
"MANIBARATHI1718" : "MANI BARATHI M",
"111623102115" : "MANISHAA V",
"mathika04" : "MATHIKAMANAL N",
"Mathumitha_27" : "MATHUMITHA V",
"midhu_0309" : "MIDHUNA K M",
"5c5v5NVXXQ" : "MOHAMED SALMAN U",
"moha_106" : "MOHAN KUMAR S",
"monika2027" : "MONIKA L",
"monish_25" : "MONISH H",
"mridu_2810" : "MRIDULA VASUDEVAN",
"Murali_2701" : "MUKKALA MURALI MANOHAR",
"MunagapatiRishitha005" : "MUNAGAPATI RISHITHA",
"Nancy_19_" : "NANCY L",
"Nanda_55" : "NANDA KISHORE P",
"eNSHStfmYF" : "NAREN VISHNU K",
"OvZRk5AH75" : "NELLORE VENKATA SAI",
"Nethra_Balan_G" : "NETHRA BALAN G",
"niki_676" : "NIKILA F",
"dir__7878" : "NILESH V",
"ravillanishanth2005" : "NISHANTH R P",
"nithinsage" : "NITHIN J",
"MR_NITHISH_26" : "NITHISH KUMAR CH N",
"nithishm_2005" : "NITHISH M",
"Nithya0221" : "NITHYA D",
"NItishrameshpp" : "NITISH R R",
"parnashanmukasaisandeep" : "PARNA SHANMUKA SAI SANDEEP",
"Pavithra_Manivannan" : "PAVITHRA M",
"penjcs_var" : "PENJENDRU VARUN",
"ranjitha2809" : "PESALA RANJITHA",
"pragadeesh_3008" : "PRAGADEESHWARAN K",
"pramodram" : "PRAMOD RAM S S",
"pras_07" : "PRASANNASHREE K",
"_riya_harshini_" : "PRIYADHARSHINI B L",
"PRIYA_-23" : "PRIYADHARSHINI S",
"pavan__05" : "PUNABAKA PAVAN KUMAR REDDY",
"Rackshita" : "RACKSHITA R",
"Raghavi_081204" : "RAGHAVI N",
"raja_28" : "RAJA RAMAN P A",
"rajasakthieswaran" : "RAJASAKTHIESWARAN G",
"Rakshitha_1304" : "RAKSHITHA P",
"S-Ramitha_7" : "RAMITHA S",
"Rangineni_SaiNithish" : "RANGINENI SAI NITHISH",
"K9xId0RviY" : "REVUNURI SOWJANYA",
"IB35hgMtwf" : "ROHITH A",
"Sachin_Kumar07" : "SACHIN KUMAR M",
"sahaana__je" : "SAHAANA J E",
"Sahana_Krishnan29" : "SAHANA G",
"SAIDHANUSH_2909" : "SAI DHANUSH A",
"Sai_krishna141" : "SAI KRISHNA S U",
"T7RixMPjnx" : "SAKTHIVEL S",
"Samhita19" : "SAMHITA S R",
"sanjanashreedd" : "SANJANA SHREE D D",
"saranya181" : "SARANYA B",
"FyYp7p7lVn" : "SARAVANAN R",
"Sarimitha" : "SARIMITHA B",
"SATHYA__C" : "SATHYA C",
"savitha2226" : "SAVITHA P",
"WzKhcOdAsT" : "SHALINI B",
"Shalini_188" : "SHALINI BASKARAN",
"Shanmathi-C" : "SHANMATHI C",
"Sharmi24" : "SHARMI S",
"Shammujeenu_7483" : "SHARMILA REDDY K",
"7TvIJb5ndZ" : "SHASHIN R",
"Shree_harine" : "SHREE HARINE R",
"shyam545" : "SHYAM SUNDAR A",
"smirti" : "SMIRTI A",
"Sneha9732" : "SNEHA HARIHARAN",
"PravalikaSomisetty" : "SOMISETTY PRAVALIKA",
"sreeharshini2005" : "SREE HARSHINI S R",
"srinivasangv1608" : "SRINIVASAN G V",
"sriranjaniS" : "SRIRANJANI S",
"vishwaa55" : "SRIVISHWAA P",
"sunil-108" : "SUNIL CHOWDRI M",
"SUYAMBULINGAMM" : "SUYAMBULINGAM M",
"decimusmaximusmeridius" : "TAMIZHARASAN J",
"Chayank__T" : "TATAVARTY CHAYANK",
"Manu_207" : "TELANAKULA VENKATA LAKSHMI MANOGNA",
"tharun_raj_28" : "THARUN RAJ D",
"mani00299" : "THUMATI MANI CHANDU",
"lalith_manjunath_reddy" : "TIPPAREDDY LALITH MANJUNATH REDDY",
"yashwanth_2912" : "VALLEPU YASHWANTH",
"9014767760" : "VANKA SANDEEP",
"N-Varnika" : "VARNIKA N",
"varsha_shree1604" : "VARSHA SHREE M",
"vasanth_6299" : "VASANTH P",
"Vasuntra" : "VASUNTRA B S",
"vigneshpraveen-official" : "VIGNESHPRAVEEN A",
"vijay07-vj" : "VIJAYAVARMAN P",
"vikramkumarofficial" : "VIKRAM KUMAR R",
"VontimittaJaswanth" : "VONTIMITTA JASWANTH KUMAR REDDY",
"Xavier_04" : "XAVIER JEEVA VASUN A",
"Yaminii02" : "YAMINI M",
"yaswanth1801" : "YASWANTH A",
"yeswanth_2005" : "YESWANTH S",
"yogalakshmissankarm" : "YOGALAKSHMI S (12-06-2006)",
"21092004" : "YOGALAKSHMI S (21-09-2004)",
"zakiya_0212" : "ZAKIYA A H",
"RazzorPets" : "ZUBAIDHU ZECKARIAH R",
"Abinash_55" : "ABINASH V",
"X6g2NMWDMx" : "MOHANA PRIYA B",
"Lavanya__2005" : "LAVANYA DEVI S",
"darwingowtham" : "DARWIN GOWTHAM K",
"RUPAKRITVIK" : "RUPAK RITVIK K P",
"avanthikaaa" : "AVANTHIKA S M",
"lxGppUCCOw" : "MANDALAPU RAMCHARAN",
"UJCyYkb26w" : "ABISHEK N",
"samadarmi" : "SAMADARMI L",
"vLMN2LmOqe" : "LOKESHWARAN A",
"uC13BEcWC9" : "HARINI K",
"Kalai0605" : "KALAIYARASI R",
"tgCYp40LtP" : "NANNAM JYOTHI SRINIVAS",
};
